version: "3.9"

services:
  web:
    build: .
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      NODE_ENV: production
      PORT: ${PORT:-8000}
    ports:
      - "${PORT:-8000}:8000"
    restart: unless-stopped
